version: '3'

services:
  ollama:
    image: ollama/ollama:0.2.1
    container_name: ollama
    user: "0:0"
    restart: unless-stopped
    # UNCOMENT THIS TO ENABLE GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    volumes:
      - "./data:/root/.ollama"
    ports:
      - 11434:11434
    hostname: ollama