version: '3'

services:
  minecraft_app:
    container_name: minecraft
    build:
      context: .
    # user: '0:0'
    volumes:
      - ./server:/server
    ports:
      - 25565:25565
      - 8123:8123

